### ISSUE TITLE
Collect and write metrics for evaluation

### ISSUE THREAD

**Issue by stefanbschneider** [stefanbschneider/mobile-env#16]
`mobile-env` needs a generic way to define and collect metrics during testing/evaluation, but not during training (too much overhead).
These metrics (eg, utility per UE and time step) should be written to a CSV file after simulation. This should allow to quantify and compare performance of different RL approaches.

In DeepCoMP, all metrics are kept in the `info` dict: https://github.com/CN-UPB/DeepCoMP/blob/master/deepcomp/env/single_ue/base.py#L383
This is later logged through a callback in TensorBoard and automatically written to CSV by RLlib.

To keep this framework-independent in `mobile-env`, I suggest to also collect metrics in the `info` dict but then write them directly to csv in Python.
This should be disabled by default and only enabled for testing.

@stwerner97 What do you think? Do you have any suggestions on how to integrate this in an easy, yet generic way?

**Comment by stwerner97** [comment]
We could define a generic signature for training/testing metrics that passes the current connections, set of basestations, and other information to the methods. The user could define a dictionary of metrics to evaluate and pass it via the configuration:

````python
self.train_metrics = {'established connections':  count_connections, ...}
self.test_metrics = {'utility per UE': utility_per_ue, ...}
````

The `step()` method then iterates over both dictionaries, evaluates all defined metrics and collects output values in the `info` dictionary:
````python
if self.train_flag:
    data = {name: metric(<signature>) for name, metric in self.train_metrics.items()}
    info = {**info, **data}
...
````
To handle the logging and saving, I would suggest to build a wrapper class. For example, we could write a wrapper that logs all results of `train_metrics` to tensorboard while training and saves those of `test_metrics` as a `.csv` file at test time. The user then imports the logger and wraps the environment:
````python
from mobile_env.wrappers.monitors import TBMonitor

env = <create environment>
env = TBMonitor(env)
...
````

Hope this helps! If you have a different suggestion, let me know. I could also make a PR over the next days if you want.

**Comment by stwerner97** [comment]
I agree that a wrapper class might not be the best choice here and generally too cumbersome for the user. Still, hard-coding logging code into the core simulation seems unclean and is inflexible (e.g. what about alternatives to TB, e.g., logging to standard output?). Maybe a generic `Montior` class could be used instead. It defines an `update`, `log` and `save` method that are called in the `step()` method of the `MComCore` class:

````python
...
self.monitor.update(<signature>, train=self.train_flag)     # updates metrics
self.monitor.log()    # logs metrics to tensorboard 
...
if done and not self.train_flag:
     self.monitor.save()     # saves results as .csv
````
The `Monitor` object could be created from the `config` passed to the simulation, i.e., from the dictionaries that define names and metrics. We can provide sensible default metrics. In my opinion, logging to tensorboard and saving results as .csv files should be disabled per default. To play around with the functionality of `mobile-env` (e.g. in Jupyter), logging to standard output might be better.

I could could draft a PR until thursday or friday, if that's okay for you?

**Comment by stefanbschneider** [comment]
Just to clarify: I'm not talking about logging in the sense of printing/logging events, eg, which funcitons are called, warnings etc.
I'm just talking about a way to define evaluation metrics, collect them during testing (for each step), and save them to csv at the end.

A dict makes sense to me: With metric name --> collected values (eg, as list/`np.array` for scalar values at each time step or as dict if we collect values per UE).
We just need to make it clear and easy for users where to populate and collect the information in this dict. Typically, this should be a place with full access to the environment, since we likely need the env to compute the metrics (eg, avg utility).

I'm fine with users manipulating the metric dict directly, but we can also hide it behind a separate object (`Monitor`).

> I could could draft a PR until thursday or friday, if that's okay for you?

That would be great! No rush; I'll be out of office the next days anyways. If you don't find the time, it's also fine, just let me know. 
If you do, could you include (avg or per UE) utility as default metric and provide a short example of how to add another custom metric + how to use the metrics (ie, save them at a configurable location)? Thanks a lot!

**Comment by stwerner97** [comment]
The pull request so far only re-factors how metrics are tracked and evaluated.

I feel like we should reconsider the storing and logging implementation: I would argue that **mobile-env** should not implement this functionality at all. The most common usage of **mobile-env** is simply as a training environment for reinforcement learning agents. Most frameworks already provide logging and storing functionality. For example, **Stable Baselines 3** provides **Tensorboard** integration:
````python
model = A2C('MlpPolicy', 'CartPole-v1', verbose=1, tensorboard_log="./a2c_cartpole_tensorboard/")
model.learn(total_timesteps=10000, tb_log_name="first_run")
````
or allows to define additional `Callback` and `Monitor` objects (see [Monitor Training and Plotting](https://stable-baselines3.readthedocs.io/en/master/guide/examples.html#basic-usage-training-saving-loading)). Both can be extended to track additional values. I suggest that **mobile-env** should only implement an interface that enables users to specify their own metrics. Then, either the RL framework or the user defines how these are stored or logged.

Implementing an integration with **Tensorboard** in **mobile-env** could also result in conflicts with the **Tensorboard** instance an RL framework would use. Also, the simulation environment usually is not informed about its usage, i.e., if it is used for training or testing or about the logging and evaluation paths. In **Stable Baselines 3** this is usually done like this:
````python
env = mobile_env.make(<simulation name>, config=<training configuration>)
model = A2C('MlpPolicy', env, verbose=1)
model.learn(...)

from stable_baselines3.common.evaluation import evaluate_policy
env = mobile_env.make(<simulation name>, config=<testing configuration>)
evaluate_policy(model, env, n_eval_episodes=10)
````
In this case, **mobile-env** does not need to know if it used for training or testing. Also, what metrics are tracked can differ between training or testing (the environment configurations can differ).

**Comment by stefanbschneider** [comment]
I agree with Tensorboard integration; that depends on the RL framework and `mobile-env` should not deal with that directly.

But we do need a way to compare different approaches after testing - even if they are trained and run with different RL frameworks or even non-RL approaches without any framework.
We also cannot simply compare reward since the reward definition may vary between different RL approaches with different MDP definitions.

That's why we should provide avg. QoE as example/default metric, which is independent of how the reward is defined.
There should be some simple way to keep track of this metric and write it to file, so it can be analyzed later on (eg, by loading it as pandas data frame).

Could be a simple flag in the env configuration, eg, a dict `metrics={}`, which can be empty by default and which contains custom metrics when desired. Then some flag `metric_filepath` with a path to where the collected metrics should be stored (eg, with columns for episode, time step, and the different metric names).

What do you think?

**Comment by stefanbschneider** [comment]
Good idea!
