### ISSUE TITLE
Thank you & Using NS3 or OMNeT++?

### ISSUE THREAD

**Issue by serapergun** [stefanbschneider/mobile-env#20]
Such a great study. 
Thank you so much for contribution to this field.
Is it possible to use this study on other network simulators such as NS3 or OMNeT++.
If it is possible, can you give us advice how to start.

Regards,
Serap

**Comment by stefanbschneider** [comment]
Hi @serapergun , thanks I'm happy to hear you like it.

In principle, you could build similar things as `mobile-env` on top of NS3 or OMNetT++. But intentionally decided against building on these existing network simulators and instead aimed at keeping `mobile-env` as simple and lightweight as possible. I.e., `mobile-env` is intentionally pure Python and a somewhat higher abstraction level (+limited scope) than NS3 and OMNet. This is to support fast and easy training with common reinforcement learning approaches that use Python and OpenAI Gym.

You can find more details in our paper: https://ris.uni-paderborn.de/download/30236/30237/author_version.pdf

I hope this helps?

**Comment by serapergun** [comment]
@stefanbschneider 
Yes
I have read you paper nearly 2 months ago. In fact I cited it my paper if it is accepted you can see in upcoming days or year :)

I try to use RL part on my OMNeT project and  it is so hard not like ns3. Because of that I am looking and searching.
Thanks for your advice.
Regards,
Serap

**Comment by stefanbschneider** [comment]
Good luck with getting your paper accepted then :) If you have more questions, feel free to open a new issue or a discussion (see the new "discussion" tab).
