### ISSUE TITLE
Feature Request: migrate from gym to gymnasium

### ISSUE THREAD

**Issue by elliottower** [stefanbschneider/mobile-env#26]
Hi, this repository is currently listed in the gymnasium [third party environments](https://gymnasium.farama.org/environments/third_party_environments/) but we are cleaning the list up to only include maintained gymnasium-compatible repositories.  

Would it be possible for it to be upgraded from gym to gymnasium? [Gymnasium](https://github.com/Farama-Foundation/Gymnasium) is the maintained version of openai gym and is compatible with current RL training libraries ([rllib](https://github.com/ray-project/ray/tree/master/rllib) and [tianshou](https://github.com/thu-ml/tianshou) have already migrated, and [stable-baselines3](https://github.com/DLR-RM/stable-baselines3/blob/e5deeed16efb57c34ccdcb14692439154d970527/docs/guide/install.rst#bleeding-edge-version) will soon).  

For information about upgrading and compatibility, see [migration guide](https://gymnasium.farama.org/content/migration-guide/) and [gym compatibility](https://gymnasium.farama.org/content/gym_compatibility/). The main difference is the API has switched to returning `truncated` and `terminated`, rather than `done`, in order to give more information and mitigate edge case issues.

**Comment by stefanbschneider** [comment]
Hi, thanks for notifying. I will try to update to the latest Gymansium version as soon as possible, closing the issue once it's ready.

**Comment by stefanbschneider** [comment]
@elliottower I just merged the changes for switching from `gym` to `gymnasium` and released mobile-env 2.0.0, which supports the latest gymnasium version.

Should I make a PR to update mobile-env in your [third-party env list](https://gymnasium.farama.org/environments/third_party_environments/)? Or will you or someone else take care of that?

**Comment by elliottower** [comment]
> @elliottower I just merged the changes for switching from `gym` to `gymnasium` and released mobile-env 2.0.0, which supports the latest gymnasium version.
> 
> Should I make a PR to update mobile-env in your [third-party env list](https://gymnasium.farama.org/environments/third_party_environments/)? Or will you or someone else take care of that?

Great to hear, thanks. And either way, I am happy to do it myself but if you want to contribute you can as well. If you wanted to you could control the wording and headline and such. We sort by number of stars and the formatting should match (not too long of a description for example) but it shouldn’t be too hard to figure out if you’re interested.

**Comment by stefanbschneider** [comment]
@elliottower Great! I opened a PR to update the docs here: https://github.com/Farama-Foundation/Gymnasium/pull/474
