### ISSUE TITLE
RLlib resource error in demo notebook

### ISSUE THREAD

**Issue by R0B1NNN1** [stefanbschneider/mobile-env#38]
Dear Stefan Schneider:

I have a question regarding the Co-lab document you uploaded on GitHub, the last section "Multi-agent RL with Raylib." When I ran "analysis = ray.tune.run("PPO", config=config, local_dir="results_rllib", stop={"timesteps_total": 30000}, checkpoint_at_end=True)", I had a warning of:

"2023-04-28 16:05:59,264 WARNING insufficient_resources_manager.py:128 -- Ignore this message if the cluster is autoscaling. You asked for 3.0 cpu and 0 gpu per trial, but the cluster only has 1.0 cpu and 0 gpu. Stop the tuning job and adjust the resources requested per trial (possibly via `resources_per_trial` or via `num_workers` for rllib) and/or add more resources to your Ray runtime. " 

I am wondering why? I thought because of the default settings of CPU and GPU. I tried to fix it by adding num_workers = 0 inside the config{}, and it has a error of cannot find the env: mobile-small-ma-v0.

**Comment by stefanbschneider** [comment]
Hi @R0B1NNN1 ,

you can control the number of CPUs Ray is supposed to using when calling `ray.init()`:

```python
ray.init(
  num_cpus=1,   # change to your available number of CPUs
  include_dashboard=False,
  ignore_reinit_error=True,
  log_to_driver=False,
)
```

This is independent of mobile_env or the env configuration. Does that help?

**Comment by R0B1NNN1** [comment]
Hi @stefanbschneider , I tried to change it to three CPUs, I still have the same problem:

"WARNING insufficient_resources_manager.py:163 -- Ignore this message if the cluster is autoscaling. No trial is running and no new trial has been started within the last 60 seconds. This could be due to the cluster not having enough resources available. You asked for 3.0 CPUs and 0 GPUs per trial, but the cluster only has 1.0 CPUs and 0 GPUs available. Stop the tuning and adjust the required resources (e.g. via the `ScalingConfig` or `resources_per_trial`, or `num_workers` for rllib), or add more resources to your cluster."

Does it work for you when you create that document? Since I want to test this using multi-agent RL.

And also, I looked at your another project DeepCoMP, may I ask for the source code, did you use the "mobile-env" or you re-write everything basic on the source code of "mobile-env"? Since I saw you mentioned that "DeepCoMP" is the project which used "mobile-env".

Thanks for replying.

**Comment by stefanbschneider** [comment]
Hi, I also run into errors when trying to run RLlib in the notebook. It also seems that some of the RLlib API has changed for the current version 2.5.1.

I'll look into it and try to fix the notebook.

**Comment by stefanbschneider** [comment]
> And also, I looked at your another project DeepCoMP, may I ask for the source code, did you use the "mobile-env" or you re-write everything basic on the source code of "mobile-env"? Since I saw you mentioned that "DeepCoMP" is the project which used "mobile-env".

DeepCoMP is open source here: https://github.com/CN-UPB/DeepCoMP

I created DeepCoMP before mobile-env. Then figured that others may want to also use the same environment and tried to pull it out and publish it separately as "mobile-env".

**Comment by R0B1NNN1** [comment]
Hi @stefanbschneider ,thanks for replying, I am trying to fix it as well. May I ask if I want to use multi agent RL, Raylib is a good choice isn't it?  Regarding to the DeepCoMP, by combining Raylib and mobile-env, we can do the same as DeepCoMP, am I correct？

Thanks for replying in advance.

**Comment by stefanbschneider** [comment]
> May I ask if I want to use multi agent RL, Raylib is a good choice isn't it? Regarding to the DeepCoMP, by combining Raylib and mobile-env, we can do the same as DeepCoMP, am I correct？

Yes, I do believe that Ray RLlib is currently the best choice for multi-agent RL. It takes some getting used to but offers lots of algorithms and many nice features + scaling.

And yes, I built DeepCoMP using RLlib and creating an environment that is similar to what is now mobile-env. So You should be able to use mobile-env and build your own multi-agent RL approach on top of it with RLlib to get a similar approach as DeepCoMP.

> And also, when I was trying to fix it, it shows me the error of " AttributeError: 'MComSmall' object has no attribute 'done' ", I am wondering what does it mean.

That's also one of the bugs I discovered. It's a leftover of moving from gym to gymnasium. It can be fixed by replacing `env.done` with `env.time_is_up` here: https://github.com/stefanbschneider/mobile-env/blob/main/mobile_env/handlers/multi_agent.py#L71
Not sure if there are more bugs though.

**Comment by R0B1NNN1** [comment]
@stwerner97 Thanks for replying. May I ask how can I replace the env.done with env.time_is_up since I am using pip install with the environment, should I download it and fix it then doing something like update it through pip or just downloaded it. I am not sure if you understand what I am saying.

**Comment by stefanbschneider** [comment]
Either you wait until I fix and release a corrected version. Then you can install/update to the version with the fix. This is the easier option, which I would recommend if you are not in a hurry.

Or, if you do not want to wait, you can check out the code from GitHub and edit it and install it locally. This is some more effort for you.

**Comment by R0B1NNN1** [comment]
Maybe I will wait until you fix it, may I ask how long will it take then? Since I am currently doing a MSc project. Thanks for replying.

**Comment by stwerner97** [comment]
Hi @stefanbschneider, I could also take a look, but wouldn't make the PR before the weekend if that's okay 😊

**Comment by stefanbschneider** [comment]
@R0B1NNN1 I opened a separate issue for your question regarding the custom SINR. Then it's easier to address separately.

@stwerner97 Thanks for offering your help! I have some work in progress. I'll push it to a separate branch and let you know, so we don't do any duplicate work. :)

**Comment by R0B1NNN1** [comment]
@stefanbschneider  Really thanks for your help, I am looking forward to the new version. And thanks for pushing a new brunch.

**Comment by stwerner97** [comment]
@stefanbschneider sounds good! 😄

**Comment by stefanbschneider** [comment]
I just merged a fix. Now RLlib should work again. It's now in a separate notebook: https://github.com/stefanbschneider/mobile-env/blob/main/examples/rllib.ipynb

Or on Colab: https://colab.research.google.com/github/stefanbschneider/mobile-env/blob/master/examples/rllib.ipynb
