### ISSUE TITLE
env.load() halts

### ISSUE THREAD

**Issue by monilouise** [stefanbschneider/mobile-env#46]
I downloaded canonical Wiki-How, but the load() function never returns after creating a virtual device. Also, ResNet() is not found, so I had to comment.

import android_env
from android_env.components.tools.easyocr_wrapper import EasyOCRWrapper
from android_env.components.coordinator import EventCheckControl

import os
os.environ["TOKENIZERS_PARALLELISM"] = "false"

#paths and parameters:
task_path = (..)
avd_name = 'Pixel 2 API 30'
android_avd_home = (...)
android_sdk_root = (...)
emulator_path = (...)
adb_path = (...)

env = android_env.load( task_path=task_path
                      , avd_name=avd_name
                      , android_avd_home=android_avd_home
                      , android_sdk_root=android_sdk_root
                      , emulator_path=emulator_path
                      , adb_path=adb_path
                      , run_headless=True
                      , mitm_config=None
                      , start_token_mark=""
                      , non_start_token_mark="##"
                      , special_token_pattern = r"\[\w+\]"
                      #, unify_vocabulary="vocab.txt"
                      , text_model=EasyOCRWrapper()
                      #, icon_model=ResNet()
                      #, icon_model=EasyOCRWrapper()
                      , with_view_hierarchy=False
                      , coordinator_args={ "vh_check_control_method": EventCheckControl.LIFT
                                         , "vh_check_control_value": 3.
                                         , "screen_check_control_method": EventCheckControl.LIFT
                                         , "screen_check_control_value": 1.
                                         }
                      )

**Comment by stefanbschneider** [comment]
Hi @monilouise , I believe your setup and comment refers to [android_env](https://github.com/google-deepmind/android_env), which is a different project than this repo (mobile-env).

Feel free to reopen the issue if I'm mistaken.
