### ISSUE TITLE
Multi-agent RL on mobile-env with Stable-Baselines3

### ISSUE THREAD

**Issue by chang2727** [stefanbschneider/mobile-env#47]
Thanks for you work!
Could you give me an example about Multi-agent RL on mobile-env with Stable-Baselines3?
Thanks!

**Comment by stefanbschneider** [comment]
Hi @chang2727 , I'm not sure if stable baselines 3 supports multi-agent RL. Afaik, stable baselines 2 did not.

Personally, I only used RLlib for multi-agent RL so far. Here's an example for multi-agent RL on mobile-env with RLlib: https://github.com/stefanbschneider/mobile-env/blob/main/examples/rllib.ipynb

**Comment by stefanbschneider** [comment]
Hi @chang2727 , I'm closing the issue for now. If you need more help, feel free to reopen it.
