### ISSUE TITLE
Possibility of developing another scenario

### ISSUE THREAD

**Issue by sinaebrahimi** [stefanbschneider/mobile-env#49]
Thanks for this amazing tool, which was essential for research!

Suppose that I want to build a scenario that is based on O-RAN xApps.
How can I ensure that each UE is connected to only one BS at a time? I don't intend to support CoMP; just a simple scenario would be OK.

**Comment by stefanbschneider** [comment]
Thanks! I'm happy to hear that you like mobile-env. It would be great if you cite it in your research.

---

An easy way to ensure that UEs only connect to one BS at a time, you can adjust `apply_action()`: https://github.com/stefanbschneider/mobile-env/blob/main/mobile_env/core/base.py#L248

There, UEs indicate which station they want to connect to. Currently, with CoMP, if they select a BS that they are already connected to, then the connection is removed. If they select a new BS, a new connection is added.

Without CoMP, you could change this as follows:
- Before adding a new connection, remove any existing connections.
- If the same BS is selected that is already connected, simply ignore the action and keep the same connection in tact.

Does that make sense?

**Comment by stwerner97** [comment]
Hi @sinaebrahimi! 😄 Glad you've found ``mobile-env`` useful.

> How can I ensure that each UE is connected to only one BS at a time?

 I think one options is to change the ``apply_action`` or ``check_connectivity`` methods in the [core simulation class](https://github.com/stefanbschneider/mobile-env/blob/main/mobile_env/core/base.py) (i.e. inherit ``MComCore`` and override these methods). You can add a condition to check if the BS is already connected to a UE then and look up what UEs are connected to a BS with the ``self.connections`` dictionary.

**Comment by stwerner97** [comment]
@stefanbschneider Glad our answers matched up😄

**Comment by sinaebrahimi** [comment]
Thank you both very much for the thorough answers! @stefanbschneider @stwerner97 
Sorry I'm seeing this too late. 

I will check it out.

**Comment by stefanbschneider** [comment]
I'm closing this ticket for now. Feel free to reopen if needed.
